### ISSUE TITLE
MS defender python script error

### ISSUE THREAD

**Issue by Ismailctest** [socfortress/Wazuh-Rules#15]
Getting the below error while running the py script, kindly support. (Given name msdefender.py)

Traceback (most recent call last):
  File "/var/ossec/integrations/msdefender.py", line 47, in <module>
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by Ismailctest** [comment]
Script link: https://github.com/socfortress/Wazuh-Rules/blob/main/Office%20Defender/defender_for_endpoint_alerts.py

**Comment by Ismailctest** [comment]
Hi Team, kindly support on this.
Script link: https://github.com/socfortress/Wazuh-Rules/blob/main/Office%20Defender/defender_for_endpoint_alerts.py
Getting the below error while running the py script, kindly support. (Given name msdefender.py)

Traceback (most recent call last):
File "/var/ossec/integrations/msdefender.py", line 47, in
response = urllib.request.urlopen(req)
File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.10/urllib/request.py", line 525, in open
response = meth(req, response)
File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
response = self.parent.error(
File "/usr/lib/python3.10/urllib/request.py", line 563, in error
return self._call_chain(*args)
File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
result = func(*args)
File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
